### ISSUE TITLE
Add machine learning features

### ISSUE THREAD

**Issue by nielsdejong** [manolotis/8point6.club#1]
Maybe we can use a deep neural network?

**Comment by manolotis** [comment]
@nielsdejong I'm really glad to see that you are so enthusiastic about it. What would you suggest though? Adding neural networks is cool and all,  but what would be the goal?

**Comment by nielsdejong** [comment]
- Collaborative Filtering
- Neuromorphic Computing
- Neural Networks
- Existential Risk
- Autonomous Vehicles
- Algorithms
- Natural Language Processing
- Turing Test
- Cognitive Computing 
- Virtual or Intelligent Agents
- Biometrics
- Swarm Intelligence

**Comment by manolotis** [comment]
@nielsdejong  That's great, you know some buzz words! But I was thinking in the context of our website...

**Comment by jottens** [comment]
Hello, I want to add Big Data. Can I add Big Data?

**Comment by manolotis** [comment]
> Hello, I want to add Big Data. Can I add Big Data?

@jottens feel free to add as much Big Data as possible!
